### ISSUE TITLE
Write docs

### ISSUE THREAD

**Issue by slashnick** [WhiteHatCP/seclab-timecard#1]
"What is this thing?"
"Where does the data come from?"
"How do I test it?"

The README would be a good place for this kind of stuff.

**Comment by xzinkus** [comment]
@nickfrostatx Please make this happen before the end of Spring quarter, if that's not possible let me know :) thanks!

**Comment by slashnick** [comment]
https://github.com/WhiteHatCP/seclab-timecard/wiki

The code itself is somewhat documented inline as well.

Re-open if you'd like me to clarify anything.
